spring:
  application:
    name: chaos-task-manager

server:
  port: ${HTTP_PORT:8888}

grpc:
  server:
    port: ${GRPC_SERVER_PORT:9999}

chaos:
  nats:
    stream: ${NATS_STREAM:TASKS}
    cmdSubject: ${NATS_CMD_SUBJECT:task.cmd.arena}
    evtSubject: ${NATS_EVT_SUBJECT:task.events.*}
    durable: ${NATS_DURABLE:task-manager}
    queue: ${NATS_QUEUE:task-manager-q}